name: Build FFmpeg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git-core \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libmp3lame-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            meson \
            ninja-build \
            pkg-config \
            texinfo \
            wget \
            nasm \
            zlib1g-dev

          sudo apt-get install -y jq

      - name: Fetch and install openAPV dependency
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/AcademySoftwareFoundation/openapv/releases/latest)
          DEPENDENCY_URL=$(echo $LATEST_RELEASE | jq -r '.assets[] | select(.name | endswith("amd64.deb")) | .browser_download_url + " " + .name' | sort -V | tail -n 1 | awk '{print $1}')
          wget $DEPENDENCY_URL -O openapv.deb
          sudo dpkg -i openapv.deb
          sudo apt-get install -f

      - name: Build FFmpeg
        run: |         
          ./configure --extra-libs="-lpthread -lm" --enable-ffplay --enable-liboapv
          make -j$(nproc)
          sudo make install

      - name: Verify run
        run: |
          oapv_app_enc
          ffmpeg -version

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
            install: >-
              git
              mingw-w64-x86_64-toolchain
              make
              yasm
              unzip
              pkg-config
              tar
              curl
            update: true
            msystem: MINGW64


      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       autoconf \
      #       automake \
      #       build-essential \
      #       cmake \
      #       git-core \
      #       libass-dev \
      #       libfreetype6-dev \
      #       libgnutls28-dev \
      #       libmp3lame-dev \
      #       libsdl2-dev \
      #       libtool \
      #       libva-dev \
      #       libvdpau-dev \
      #       libvorbis-dev \
      #       libxcb1-dev \
      #       libxcb-shm0-dev \
      #       libxcb-xfixes0-dev \
      #       meson \
      #       ninja-build \
      #       pkg-config \
      #       texinfo \
      #       wget \
      #       nasm \
      #       zlib1g-dev
      #     sudo apt-get install -y jq \
      #       mingw-w64

      - name: Fetch and install openAPV dependency
        shell: msys2 {0}
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/AcademySoftwareFoundation/openapv/releases/latest)
          DEPENDENCY_URL=$(echo $LATEST_RELEASE | jq -r '.assets[] | select(.name | endswith("win64.zip")) | .browser_download_url + " " + .name' | sort -V | tail -n 1 | awk '{print $1}')
          wget $DEPENDENCY_URL -O openapv.zip
          sudo unzip openapv.zip -d /openapv

          echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/openapv/OpenAPV-0.2.0.1-win64/lib/pkgconfig" >> $GITHUB_ENV
          echo "CFLAGS=I$GITHUB_WORKSPACE/openapv/OpenAPV-0.2.0.1-win64/include" >> $GITHUB_ENV
          echo "LDFLAGS=L$GITHUB_WORKSPACE/openapv/OpenAPV-0.2.0.1-win64/lib" >> $GITHUB_ENV
          echo "PATH=L$GITHUB_WORKSPACE/openapv/OpenAPV-0.2.0.1-win64/bin" >> $GITHUB_ENV

      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          ./configure --prefix="$GITHUB_WORKSPACE/build" --pkg-config-flags="--static" \
          --extra-cflags="$CFLAGS" \ 
          --extra-ldflags="$LDFLAGS" \
          --target-os=mingw32 --arch=x86_64 --enable-cross-compile --cross-prefix=x86_64-w64-mingw32- \
          --enable-sdl2 --enable-gpl --enable-ffplay --enable-liboapv \

          make -j$(nproc)
          make install

